[package]
name = "rpsbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rand = "0.8.5"
serenity = "0.11.2"
tokio = {version = "1.18.2", features = ["full"]}
